[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
parser = {path = "../parser"}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
